---
- src: http://github.com/idealista/rsyslog_role
  version: 2.2.2
  name: rsyslog_role

- src: https://github.com/idealista/consul_role
  version: 1.10.1
  name: consul_role

- src: https://github.com/idealista/postgresql_role
  version: 2.0.0
  name: postgresql_role

- src: https://github.com/idealista/pgbouncer_role
  version: 1.0.0
  name: pgbouncer_role
