---

- block:  # Debian/Ubuntu
    - name: Add repository apt-key
      ansible.builtin.apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ apt_repository_keys }}"
      when: apt_repository_keys | length > 0

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: true
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "Debian"
  tags: add_repo


# timescaledb (if enable_timescale is defined)
- block:
    # Debian based
    - name: Add TimescaleDB repository apt-key
      ansible.builtin.apt_key:
        url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add TimescaleDB repository
      ansible.builtin.apt_repository:
        repo: "deb https://packagecloud.io/timescale/timescaledb/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

  environment: "{{ proxy_env | default({}) }}"
  when:
    - installation_method == "repo"
    - enable_timescale is defined
    - enable_timescale | bool
  tags: add_repo

...
