---

# when postgresql NOT exists
- block:
    - name: Patroni | check that data directory "{{ postgresql_data_dir }}" is not initialized
      ansible.builtin.stat:
        path: "{{ postgresql_data_dir }}/PG_VERSION"
      register: pgdata_initialized
      when: patroni_cluster_bootstrap_method == "initdb"

    - name: Patroni | data directory check result
      ansible.builtin.fail:
        msg: "Whoops! data directory {{ postgresql_data_dir }} is already initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - pgdata_initialized.stat.exists
  when:
    - not postgresql_exists | bool
    - not (postgresql_cluster_maintenance|default(false)|bool)   # exclude for config_pgcluster.yml

# when postgresql exists
- block:
    - name: Patroni | check that data directory "{{ postgresql_data_dir }}" is initialized
      ansible.builtin.stat:
        path: "{{ postgresql_data_dir }}/PG_VERSION"
      register: pgdata_initialized

    - name: Patroni | data directory check result
      ansible.builtin.fail:
        msg: "Whoops! data directory {{ postgresql_data_dir }} is not initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - not pgdata_initialized.stat.exists
  when:
    - postgresql_exists | bool
    - not (postgresql_cluster_maintenance|default(false)|bool)   # exclude for config_pgcluster.yml

- block:
    - name: Patroni | Check if Patroni is running
      uri:
        url: "http://{{ inventory_hostname }}:8008/patroni"
        return_content: true
        status_code: 200
      register: resultado_patroni
      ignore_errors: true

    - name: Patroni | Set Patroni status
      set_fact:
        patroni_is_running: "{{ resultado_patroni.status == 200 and 'running' in resultado_patroni.content }}"

    - name: Patroni | Show Patroni status
      debug:
        msg: "Patroni is running"
      when: patroni_is_running
